"""add min/max points

Revision ID: 3cdd26bd40c3
Revises: 04440ebbb70c
Create Date: 2025-01-14 23:56:41.639169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cdd26bd40c3'
down_revision: Union[str, None] = '04440ebbb70c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('min_points', sa.SMALLINT(), nullable=False))
    op.add_column('results', sa.Column('max_points', sa.SMALLINT(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('results', 'max_points')
    op.drop_column('results', 'min_points')
    # ### end Alembic commands ###
