"""add is_diary_on to user

Revision ID: c47392208558
Revises: 1ef436b54ad2
Create Date: 2025-01-17 09:33:07.952395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c47392208558'
down_revision: Union[str, None] = '1ef436b54ad2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_diary_on', sa.Boolean(), nullable=False, server_default="true"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_diary_on')
    # ### end Alembic commands ###
