"""make question2variant as many to many

Revision ID: e2141e8c6647
Revises: c47392208558
Create Date: 2025-01-17 10:06:44.947791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2141e8c6647'
down_revision: Union[str, None] = 'c47392208558'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_to_variant',
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('variant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['variants.id'], )
    )
    op.drop_constraint('variants_question_id_fkey', 'variants', type_='foreignkey')
    op.drop_column('variants', 'question_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('variants', sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('variants_question_id_fkey', 'variants', 'questions', ['question_id'], ['id'])
    op.drop_table('question_to_variant')
    # ### end Alembic commands ###
